clear;
number = 4;
problem.objective = @test_opti;
problem.x0 =[59,9,52,16];
problem.lb =[35 1 35 1 ];
problem.ub =[ 99.9 99.9 99.9 99.9 ];
problem.rngstate= [];
problem.solver='simulannealbnd';
oldopts  = saoptimset('simulannealbnd');
problem.options = saoptimset(oldopts,'PlotFcns',@saplotbestf);
[x,fval,exitflag,output] = simulannealbnd(problem);